### PR TITLE
SOL-11 [FE] Create markup for campaign creation

### PR DESCRIPTION
**Pull request by jasonchuasun**
## Issue Link
- Backlog [link](https://framgiaph.backlog.com/view/SPH_SOLIDITY-11)

## Target Page | Component | Function
- /create-campaign

## Pre-condition
- install necessary packages.

## Steps | Commands
1.  Open FE directory - `cd fe`
2. Install packages - `yarn install`
3. Visit the Create Campaign page by clicking `Start a campaign` in the home page
4. Test out the form and its validation

## Expected Output
- Add here

## Definition of Done
- Page redirect is working
- Form validation is working
- Form submission is working - form data is printed in the console (temporary)

## Test View Points
- [ ] Add here

## Notes
N/A

## Screenshots | Recordings
image
image

### General
- [ ] Does the code meet the requirements of the project?
- [ ] Is the code readable and maintainable?
- [ ] Are there any unnecessary or redundant lines of code?
- [ ] Are there any long methods or functions that should be refactored?
- [ ] Are there any performance issues?

### Functionality
- [ ] Are there any logical errors?
- [ ] Are edge cases handled properly?
- [ ] Are there any potential security vulnerabilities?

### Code Style
- [ ] Does the code adhere to the project's coding standards?
- [ ] Are variable and function names descriptive and meaningful?
- [ ] Is there proper use of comments and documentation?
- [ ] Is the code properly formatted? Are indentation, spacing, and formatting consistent?

### Security
- [ ] Is the website secure from common attacks?
- [ ] Are inputs properly validated and sanitized?
- [ ] Are sensitive data and credentials properly protected?

### Testing
- [ ] Are there sufficient test cases?
- [ ] Do the test cases cover all functionality?
- [ ] Are the test cases properly written and documented?

### Additional Comments
- [ ] Are there any other issues or concerns with the code?
- [ ] Are there any suggestions for improvement?
- [ ] Are there any positive aspects of the code that should be highlighted?

### CODE REVIEW

**Comment by ipilikent** [comment]
**Comment**

• Problem
  - The height of the Story Field is wrong
   
• Expected Output
  - Story Field - The height should be 129px

**Comment by jasonchuasun** [comment]
> **Comment**
> 
> • Problem
> 
> * The height of the Story Field is wrong
> 
> • Expected Output
> 
> * Story Field - The height should be 129px

Updating height to 128px - divisible by 8.

**Comment by ipilikent** [comment]
## Approved PR
-  All displayed the same as the Figma design
- Can inputs the fields
- The validation messages are working
- Can select date
- Can set Goals
- Can click Upload Image button
- Can click Submit Application button

## Proof
<details>

Sol-11 - FE Campaign Form

</details>

Test Case: https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=637322504
-----
- Total Test time:  0.5 hr.
- Total Comments: 1
- Total Iterations: 0

**Review by johnpaul-sun — APPROVED** [review]
Approved ✅

Review Time: 30 mins
Comments: 0
IT: 0

**Review by kenorenzsun — APPROVED** [review]

**Pull request merged**
