### PR TITLE
SOL-34 [Integrate] Integrate smart contract function for updating campaign

### PR DESCRIPTION
**Pull request by kenorenzsun**
## Issue Link
- [Backlog link
](https://framgiaph.backlog.com/view/SPH_SOLIDITY-34)
## Target Page | Component | Function
- `/edit-campaign/3`
## Pre-condition
- go to a specific campaign page then click edit icon near title

## Steps | Commands
1. Add here

## Expected Output
- You can edit your campaign

## Definition of Done
- Add here

## Test View Points
- [ ] Add here

## Notes
N/A

## Screenshots | Recordings
Add here

### General
- [ ] Does the code meet the requirements of the project?
- [ ] Is the code readable and maintainable?
- [ ] Are there any unnecessary or redundant lines of code?
- [ ] Are there any long methods or functions that should be refactored?
- [ ] Are there any performance issues?

### Functionality
- [ ] Are there any logical errors?
- [ ] Are edge cases handled properly?
- [ ] Are there any potential security vulnerabilities?

### Code Style
- [ ] Does the code adhere to the project's coding standards?
- [ ] Are variable and function names descriptive and meaningful?
- [ ] Is there proper use of comments and documentation?
- [ ] Is the code properly formatted? Are indentation, spacing, and formatting consistent?

### Security
- [ ] Is the website secure from common attacks?
- [ ] Are inputs properly validated and sanitized?
- [ ] Are sensitive data and credentials properly protected?

### Testing
- [ ] Are there sufficient test cases?
- [ ] Do the test cases cover all functionality?
- [ ] Are the test cases properly written and documented?

### Additional Comments
- [ ] Are there any other issues or concerns with the code?
- [ ] Are there any suggestions for improvement?
- [ ] Are there any positive aspects of the code that should be highlighted?

### CODE REVIEW

**Comment by ipilikent** [comment]
Comment
• Problem
- It's very quick to return to the campaign details
- After update there are 3 toast displays


• Expected Output
- Return to the campaign details after a few seconds
- There should be only one toast after the campaign update

**Comment by ipilikent** [comment]
## Approved PR
- Can update/edit his campaign
- The validations messages are displayed
- After update the campaign can redirect to the campaign details page
- Can go back
- The pen icon is displayed and clickable

## Proof
<details>

Sol- 34 Integrate Update campaign

</details>

Test Case: https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=896446223
-----
- Total Test time:  1 hr.
- Total Comments: 1
- Total Iterations: 1

**Review by ipilikent — APPROVED** [review]

**Review by arden-dave-sun — DISMISSED** [review]
Approved ✅
Review time: 30 mins
Comment: 0
Iteration: 0

**Review by wylenjoan — APPROVED** [review]
Approved :white_check_mark:
Review time: 30 mins
Comment: 0
Iteration: 0
Working:
<details>
<summary> Edit campaign </summary>

image

</details>

**Review by arden-dave-sun — APPROVED** [review]

**Pull request merged**
