### PR TITLE
SOL-57 [Improvement] Add required Metamask, title and icon

### PR DESCRIPTION
**Pull request by johnpaul-sun**
## Issue Link
- [Backlog link](https://framgiaph.backlog.com/view/SPH_SOLIDITY-57)

## Target Page | Component | Function
- /

## Pre-condition
- n/a

## Steps | Commands
1. n/a

## Expected Output
- It should display the Title and Icon in the title bar

## Definition of Done
- Added Wallet setup steps in README

## Test View Points
- [ ] Add here

## Notes
N/A

## Screenshots | Recordings
image

### General
- [ ] Does the code meet the requirements of the project?
- [ ] Is the code readable and maintainable?
- [ ] Are there any unnecessary or redundant lines of code?
- [ ] Are there any long methods or functions that should be refactored?
- [ ] Are there any performance issues?

### Functionality
- [ ] Are there any logical errors?
- [ ] Are edge cases handled properly?
- [ ] Are there any potential security vulnerabilities?

### Code Style
- [ ] Does the code adhere to the project's coding standards?
- [ ] Are variable and function names descriptive and meaningful?
- [ ] Is there proper use of comments and documentation?
- [ ] Is the code properly formatted? Are indentation, spacing, and formatting consistent?

### Security
- [ ] Is the website secure from common attacks?
- [ ] Are inputs properly validated and sanitized?
- [ ] Are sensitive data and credentials properly protected?

### Testing
- [ ] Are there sufficient test cases?
- [ ] Do the test cases cover all functionality?
- [ ] Are the test cases properly written and documented?

### Additional Comments
- [ ] Are there any other issues or concerns with the code?
- [ ] Are there any suggestions for improvement?
- [ ] Are there any positive aspects of the code that should be highlighted?

### CODE REVIEW

**Review by jasonchuasun — DISMISSED** [review]

**Comment by jasonchuasun** [comment]
Approved ✅

Review Time: 10mins
Comments: 0
IT: 0

**Review by chevyB — DISMISSED** [review]

**Review by wylenjoan — COMMENTED** [review]
Can you add these lines in `smart_contract/README.md`?
[Commands.md](https://github.com/framgia/sph-solidity/files/11966619/Commands.md)

**Review by wylenjoan — APPROVED** [review]
Approved :white_check_mark:
Review time: 15 mins
Comment: 0
Iteration: 0

**Review by chevyB — APPROVED** [review]

**Comment by ipilikent** [comment]
## Approved PR
- The Title and Icon changed and displayed

## Proof
<details>

image

</details>

-----
- Total Test time: 0.10 hr.
- Total Comments: 0
- Total Iterations: 0

**Review by ipilikent — APPROVED** [review]

**Pull request merged**
