### PR TITLE
SOL-64 [Integrate] Integrate smart contract function for viewing user's donations across all campaigns

### PR DESCRIPTION
**Pull request by kenorenzsun**
## Issue Link
- [Backlog link](https://framgiaph.backlog.com/view/SPH_SOLIDITY-64)

## Target Page | Component | Function
- '/profile/' + donations tab

## Pre-condition
- Connect to wallet

## Steps | Commands
1. Add here

## Expected Output
- should display donations of user 
- should be paginated

## Definition of Done
- donations of user are displayed properly 

## Test View Points
- [ ] Add here

## Notes
N/A

## Screenshots | Recordings
Add here

### General
- [ ] Does the code meet the requirements of the project?
- [ ] Is the code readable and maintainable?
- [ ] Are there any unnecessary or redundant lines of code?
- [ ] Are there any long methods or functions that should be refactored?
- [ ] Are there any performance issues?

### Functionality
- [ ] Are there any logical errors?
- [ ] Are edge cases handled properly?
- [ ] Are there any potential security vulnerabilities?

### Code Style
- [ ] Does the code adhere to the project's coding standards?
- [ ] Are variable and function names descriptive and meaningful?
- [ ] Is there proper use of comments and documentation?
- [ ] Is the code properly formatted? Are indentation, spacing, and formatting consistent?

### Security
- [ ] Is the website secure from common attacks?
- [ ] Are inputs properly validated and sanitized?
- [ ] Are sensitive data and credentials properly protected?

### Testing
- [ ] Are there sufficient test cases?
- [ ] Do the test cases cover all functionality?
- [ ] Are the test cases properly written and documented?

### Additional Comments
- [ ] Are there any other issues or concerns with the code?
- [ ] Are there any suggestions for improvement?
- [ ] Are there any positive aspects of the code that should be highlighted?

### CODE REVIEW

**Review by wylenjoan — DISMISSED** [review]
Approved :white_check_mark:
Review time: 20 mins
Comment: 0
Iteration: 0
Working:
<details>
<summary> Fetch user's donations </summary>

image

</details>

**Review by johnpaul-sun — DISMISSED** [review]
Approved ✅

Review Time: 15 mins
Comments: 0
IT: 0

**Comment by ipilikent** [comment]
Comment
• Problem
- The size of the table has decreased
image

• Expected Output
- The size of the table is the same as that of the donators, the size should be width 1135.2px
image

**Comment by ipilikent** [comment]
## Approved PR
-  All displayed the same as the Figma design
- The user can view the donations
- The pagination is working
   - more than 6 rows display the pagination
   - less than 6 rows no pagination display
-  Displayed donations of user

## Proof
<details>

Sol- 64 Integrate Donations

</details>

Test Case: https://docs.google.com/spreadsheets/d/114GrEn-LQQ8saIvjz9zqenuk05qmO4dN/edit#gid=1122662191
-----
- Total Test time:  1 hr.
- Total Comments: 1
- Total Iterations: 0

**Review by ipilikent — APPROVED** [review]

**Review by wylenjoan — APPROVED** [review]

**Review by johnpaul-sun — APPROVED** [review]

**Pull request merged**
